language: ruby
rvm:
  - 2.2.2
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database reminders_test;' -U postgres"
  - "bundle exec rake db:migrate"
script: "bundle exec rspec spec/**/*_spec.rb"
services: postgresql
